version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bash -c "sleep 2 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    links:
      - db
    volumes:
      - .:/project
    ports:
      - "8000:8000"
    depends_on:
      - db