# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentialsmodel',
            name='credential',
        ),
        migrations.RemoveField(
            model_name='credentialsmodel',
            name='label',
        ),
        migrations.AddField(
            model_name='credentialsmodel',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
