# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 08:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_project', '0003_auto_20160913_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentialsmodel',
            name='code',
        ),
        migrations.AddField(
            model_name='credentialsmodel',
            name='credential',
            field=oauth2client.contrib.django_util.models.CredentialsField(null=True),
        ),
        migrations.AlterField(
            model_name='credentialsmodel',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
